# Generated by Django 6.0.2 on 2026-03-17 20:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmonitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowingrecord',
            name='proof_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
