# Generated by Django 6.0.2 on 2026-03-18 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmonitor', '0002_borrowingrecord_proof_image_tasksubmission_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='taskmonitor.equipment'),
        ),
    ]
