# Generated by Django 6.0.2 on 2026-03-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmonitor', '0003_task_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='equipment_action',
            field=models.CharField(blank=True, choices=[('checkout', 'Checkout'), ('return', 'Return')], max_length=10, null=True),
        ),
    ]
