# Generated by Django 6.0.2 on 2026-03-21 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmonitor', '0004_task_equipment_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='borrowed_by',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='task',
            name='is_borrowing',
            field=models.BooleanField(default=False),
        ),
    ]
