# Generated by Django 6.0.2 on 2026-03-22 07:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmonitor', '0005_task_borrowed_by_task_is_borrowing'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('no_signal', 'No Signal'), ('bad_weather', 'Bad Weather'), ('location_issue', 'Location Issue'), ('equipment_issue', 'Equipment Issue'), ('other', 'Other')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved', models.BooleanField(default=False)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='taskmonitor.task')),
            ],
        ),
    ]
