# Generated by Django 6.0.2 on 2026-04-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmonitor', '0006_taskreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksubmission',
            name='validation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
